[
	{
		ID:"1",
		Title: "Box IA",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "active",
		cardColor: "light-blue darken-1",
		cardIcon: "mdi-action-lock",
		cardIconColor: "black"
	},
	{
		ID:"2",
		Title: "EFB MCM",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "",
		cardIcon: "",
		cardIconColor: ""
	},
		{
		ID:"3",
		Title: "Box PM",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "light-blue darken-1",
		cardIcon: "mdi-action-lock",
		cardIconColor: "black"
	},
		{
		ID:"4",
		Title: "Mobility Pilots",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "",
		cardIcon: "",
		cardIconColor: ""
	},
]