[
	{
		ID:"1",
		meetingTitle: "Box IA",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "",
		cardIcon: "",
		cardIconColor: ""
	},
	{
		ID:"2",
		meetingTitle: "EFB MCM",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "",
		cardIcon: "",
		cardIconColor: ""
	},
		{
		ID:"3",
		meetingTitle: "Box PM",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "",
		cardIcon: "",
		cardIconColor: ""
	},
		{
		ID:"4",
		meetingTitle: "Mobility Pilots",
		description: "Here is some more information about this product that is only revealed once clicked on. Here is some more information about this product that is only revealed once clicked on.",
		startDate: "",
		hour: "",
		minute: "",
		meridian: "",
		recurring: true,
		occursEvery: "Occurs every Tue. 1300 hrs",
		organizer: "Carlos Gonzalez",
		dialIn: "555-555-5555",
		dcsLink: "http://somelink.here/andid",
        status: "",
		cardColor: "",
		cardIcon: "",
		cardIconColor: ""
	},
]